---
- name: Installing Mysql and dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
  notify: mysql_restart

- name: Starting and Enabing Mysql service
  service: name=mysql state=started enabled=yes
  ignore_errors: yes

