---
- name: Downloading rpm for mysql
  get_url: url=http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm dest=/opt/

- name: Installing repo
  yum: name=/opt/mysql-community-release-el6-5.noarch.rpm state=present
  ignore_errors: yes

- name: Installing mysql server
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - mysql
    - mysql-server
    - MySQL-python
    - libselinux-python

- name: Starting and Enabling mysql
  service: 
    name: mysqld
    state: started
    enabled: yes 

